version: '3.8'

services:
  dask-worker:
    image: daskdev/dask:latest
    container_name: dask-worker
    command: dask-worker tcp://18.218.28.236:8786
    networks:
      - dask-network
    volumes:
      - /home/ubuntu/dask-python-/data:/data
    restart: always
  
networks:
  dask-network:
    driver: bridge
