version: '3.8'

services:
  dask-worker:
    image: daskdev/dask:latest
    container_name: dask-worker
    command: dask-worker tcp://<IP_DEL_SERVIDOR_DEL_SCHEDULER>:8786
    networks:
      - dask-network
    volumes:
      - dask-data:/data
    restart: always

networks:
  dask-network:
    driver: bridge

volumes:
  dask-data:
